### ISSUE TITLE
Can't execute test task

### ISSUE THREAD

**Issue by denysstepanyuk** [epishev/test_task#1]
@epishev I can't execute tests using your README file. 
I see next error --> "can't find module cypress-cucumber-preprocessor". Please check everything once more and update steps in TEST FRAMEWORK section. 
Thanks.

**Comment by epishev** [comment]
@denysstepanyuk
Thank you for your feedback! Unfortunately there wasn't "cypress-cucumber-preprocessor" in dependencies of package.json.
I have commited the following changes:
1) Added "cypress-cucumber-preprocessor": "^1.13.1"  to dependencies
2) Added "ignoreTestFiles": ["*.js", "*.md"] to cypress.json
3) Added "Background:" steps to features
4) Added additional steps

Please try again to run the tests!
Thank you in advanced!
